<?php

namespace Tests\Feature;

use App\CategoryMaster;
use App\User;
use App\UserAsset;
use Tests\TestCase;
use Tests\SeedingDatabase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class EditUserAssetTest extends TestCase
{
    use SeedingDatabase;
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->states('withAsset')->create();
    }

    /**
     * @test
     */
    public function should_user_assetのリストをJsonで返却する()
    {

        $this->assertDatabaseHas('user_assets', ['user_id' => $this->user->id]);
        $this->assertDatabaseHas('category_masters', ['id' => 1]);

        $request = $this->actingAs($this->user)
            ->json('get', route('categorize.view'));

        $category = CategoryMaster::where('section_id',1)->first();
        $uAsset = UserAsset::where('user_id', 1)->first();
        $expected = [
            'selectInfo' => [
                1 => [$category->id => $category->name],
            ],
            'userAssetList' => [
                1 => [
                    'name' => $uAsset->name,
                    'categories' => [
                        1 => $uAsset->categoryMasters()->first()->id,
                    ],
                    'value' => $uAsset->value,
                ]
            ]
        ];

        $request->assertStatus('200');
        $request->assertJson($expected);
    }
}
